runtime: nodejs20
entrypoint: node server.js

env_variables:
  NODE_ENV: "production"
  GEMINI_API_KEY: "AIzaSyD79FO9aTI5n0zJUbEPmPLyTbmXlgGzitg"

handlers:
  - url: /static
    static_dir: public
  - url: /.*
    script: auto

automatic_scaling:
  max_instances: 20